config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get "/about" => "pages#about"
    get "/faq" => "pages#faq"
    get "/contact" => "pages#contact"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def faq
    end
    
    def contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <%= link_to image_tag('follow-church-250.png',{:style=>'margin-top:10px;'}), root_path %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <!-- <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "Contact", contact_path %></li> -->
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowUp.Church - Follow Up With New Contacts And Converts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <%= yield %>
        </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container forty thin">
    <h1 class="center">About FollowUp.Church</h1>
    <div class="thousand">
        <%= image_tag('montoya-family.jpg', class: "img-thumbnail pull-right familyAbout") %>
        <p>My name is a Pastor Estevan Montoya, of the <a href="http://www.MVBCTaos.org" target="_blank">Mountain View Baptist Church</a> in Taos, NM. Having started a church plant, I know the value of keep track of people you meet. Chances are, you value the ability to follow up with people. You know the value of keeping contact. You may want to follow up for one the following reasons:</p>
        <ul>
            <li>You want to share the Gospel</li>
            <li>You want to get them in to a class</li>
            <li>You want to help them get baptized</li>
            <li>You want to help them join your church</li>
            <li>You know that your ministry is a place to help them grow</li>
        </ul>
        <p>The list can go on and on. Either way, it is vital to follow up with new contacts and converts. This web application with help you kepp track and follow up with people for the Glory of God!</p>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="container center forty thin">
    <h1>Contact Us</h1>
    <div class="thousand">
    </div>
</div>

app/views/pages/faq.html.erb
<div class="container center forty thin">
    <h1>Got Questions?</h1>
    <div class="thousand">
    </div>
</div>

app/views/pages/home.html.erb
<div class="container center forty thin">
    <h1><strong>PASTORS AND CHURCH PLANTERS</strong>:<br />Don't let anyone "slip through the cracks".</h1>
    <h2>A <strong>simple website</strong> for your church to keep track of new contacts and converts. Your ministry can continue to bring people Christ and help them grow in the Lord.</h2>
    <div class="forty">
        <h4 class="forty">Join the waiting list to be notified when we launch.</h4>
        <div class="center homeOptin">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="email@example.com">
                <span class="input-group-btn">
                <button class="btn btn-primary" type="button">Join!</button>
                </span>
            </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </div>
</div>